projects:
  amplifyDatasource:
    schemaPath: amplify/backend/api/amplifyDatasource/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: cn-north-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
